export const GET_PERSON ="GET_PERSON";
export const ADD_PERSON ="ADD_PERSON";
export const DELET_PERSON ="DELET_PERSON";
export const PERSON_LOADING ="PERSON_LOADING";
export const PRESENT_PERSON ="PRESENT_PERSON";


export const USER_LOADING ="USER_LOADING";
export const USER_LOADED ="USER_LOADED";
export const AUTH_ERROR ="AUTH_ERROR";
export const LOGIN_SUCCESS ="LOGIN_SUCCESS";
export const LOGIN_FAIL ="LOGIN_FAIL";
export const LOGOUT_SUCCESS ="LOGOUT_SUCCESS";
export const REGISTER_SUCCESS ="REGISTER_SUCCESS";
export const REGISTER_FAIL ="REGISTER_FAIL";
export const GET_ERRORS ="GET_ERRORS";
export const CLEAR_ERRORS ="CLEAR_ERRORS";


